#!/bin/bash

# Default layout (can be bsp, stack, or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Padding settings
yabai -m config top_padding 6
yabai -m config bottom_padding 6
yabai -m config left_padding 6
yabai -m config right_padding 6
yabai -m config window_gap 6

# Mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap

# Automatically balance spaces when windows are moved
yabai -m config auto_balance on

# Disable specific apps from being managed
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Outlook$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off

# Configure external bar
yabai -m config external_bar all:32:0

# Focus follows mouse and autofocusing
yabai -m config focus_follows_mouse autofocus
